"""empty message

Revision ID: 2765af924ad1
Revises: 6ac731c061af
Create Date: 2018-11-27 04:41:56.728312

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '2765af924ad1'
down_revision = '6ac731c061af'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('ih_area_info', 'is_delete',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.alter_column('ih_facility_info', 'is_delete',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.alter_column('ih_house_image', 'is_delete',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.alter_column('ih_house_info', 'is_delete',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.alter_column('ih_order_info', 'is_delete',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.alter_column('ih_user_profile', 'is_delete',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('ih_user_profile', 'is_delete',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.alter_column('ih_order_info', 'is_delete',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.alter_column('ih_house_info', 'is_delete',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.alter_column('ih_house_image', 'is_delete',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.alter_column('ih_facility_info', 'is_delete',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.alter_column('ih_area_info', 'is_delete',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    # ### end Alembic commands ###
